# Generated by Django 3.1.7 on 2021-12-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reto',
            name='progreso',
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.reto')),
            ],
            options={
                'db_table': 'progreso',
            },
        ),
    ]
