# Generated by Django 3.1.7 on 2021-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_auto_20211229_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
